import os
import glob
import subprocess
import json
from submodule.stimulus_generation import generate_stimulus_file

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.abspath(os.path.join(base_dir, "../data/thermal"))
    
    stimulus_txt_path = os.path.join(base_dir, "stimulus.txt")
    hw_log_path = os.path.join(base_dir, "hw_resp.txt")
    output_results_path = os.path.join(base_dir, "far_results.json")
    
    chunk_files = sorted(glob.glob(os.path.join(data_dir, "thermal_chunk_*.npy")))
    if not chunk_files:
        print("[!] CRITICAL: No chunk files found in", data_dir)
        return

    # Sweep: 2.0 to 5.0 at 0.5 intervals
    snr_thresholds = [2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
    scale = 64.0 
    
    # Initialize metric tracking
    results = {
        str(snr): {
            "hw_threshold_int": int(snr * scale), 
            "false_positives": 0, 
            "events_processed": 0
        } for snr in snr_thresholds
    }

    for snr in snr_thresholds:
        hw_thr = int(snr * scale)
        print(f"\n{'='*50}")
        print(f"[*] SWEEPING THRESHOLD: SNR {snr} (HW INT: {hw_thr})")
        print(f"{'='*50}")
        
        # Iterating over the full 2.1M dataset for statistical validity
        for chunk_file in chunk_files:
            chunk_name = os.path.basename(chunk_file)
            print(f"[*] Processing: {chunk_name}")
            
            # 1. Generate Stimulus
            generate_stimulus_file(chunk_file, stimulus_txt_path, scale)
            
            # 2. Execute Vivado CLI Simulation
            elab_cmd = [
                "xelab", "-debug", "typical", "-top", "tb_hilo_trigger", 
                "-snapshot", "tb_snap", "-generic_top", f"THRESHOLD={hw_thr}"
            ]
            sim_cmd = ["xsim", "tb_snap", "-R"]
            
            try:
                subprocess.run(elab_cmd, check=True, stdout=subprocess.DEVNULL)
                subprocess.run(sim_cmd, check=True, stdout=subprocess.DEVNULL)
            except subprocess.CalledProcessError as e:
                print(f"[!] CRITICAL: Vivado simulation failed. {e}")
                return
            
            # 3. Extract Metrics
            if os.path.exists(hw_log_path):
                with open(hw_log_path, 'r') as f:
                    lines = f.readlines()
                    # Count occurrences of '1' indicating a trigger
                    fp_count = sum(1 for line in lines if '1' in line.strip())
                
                results[str(snr)]["false_positives"] += fp_count
                # Retrieve actual event count directly from array shape to handle irregular last chunks
                events_in_chunk = np.load(chunk_file, mmap_mode='r').shape[0]
                results[str(snr)]["events_processed"] += events_in_chunk 
                
                os.remove(hw_log_path)
            else:
                print(f"[!] WARNING: {hw_log_path} was not generated by Vivado.")
            
            if os.path.exists(stimulus_txt_path):
                os.remove(stimulus_txt_path)

        # Periodic save after each threshold sweep
        with open(output_results_path, 'w') as f:
            json.dump(results, f, indent=4)

    print(f"\n[*] Execution complete. Final FAR data logged to {output_results_path}")

if __name__ == "__main__":
    main()